### ISSUE TITLE
Feature request: Append to existing list

### ISSUE THREAD

**Issue by davidolrik** [campos-ddc/yaml-patch#3]
It would be nice to be able to append and element to an existing list.

I was thinking the syntax currently used for patching every element would be nice.
I can't think of an example where I would change all elements to the same value, where as I frequently wants to add an element to the end of a list.

**Comment by campos-ddc** [comment]
Probably better to use `+=` which is somewhat consistent with `jq`. What do you think?

**Comment by davidolrik** [comment]
That could also work, and won't break backwards compatibility which is always a good thing.

**Comment by campos-ddc** [comment]
Just out of curiosity, are you using this as a cmdline tool, or as a python module?

**Comment by davidolrik** [comment]
My first use case was as a cmdline tool, so I could remove [ytt](https://carvel.dev/ytt/) as a dependency for simple stuff.

**Comment by campos-ddc** [comment]
Should work in 1.1.0 (available in PyPI).

Example is [here](https://github.com/campos-ddc/yaml-patch/tree/v1.1.0#append-a-single-value), make sure to pass the item being appended as a list (so `path+=['new_item']` instead of `path+='new_item'`)

**Comment by campos-ddc** [comment]
Also, I'd generally recommend using [yq](https://github.com/mikefarah/yq) for any command line based patching when possible. I think it does not keep formatting and comments, but it has a lot more features and is generally a more standard tool (since it's based in jq)

Can be used to append items like this: `yq e '.path += ["new_item"]' -i myfile.yml`

**Comment by davidolrik** [comment]
Agreed - but in this context, I'm already using poetry to pull in dependencies - so pulling in yaml-patch, saves me one more external dependency =)

Thanks for the quick patch!
